[2024-09-04 14:30:13,242] MacBook-Pro/INFO/root: Waiting for workers to be ready, 0 of 10 connected
[2024-09-04 14:30:13,779] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_e07f87b5e8cf4c7f9edc27cb2ca79cf3 (index 0) reported as ready. 1 workers connected.
[2024-09-04 14:30:13,781] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_ca3093a24fed4c15ba543665b537a2f1 (index 1) reported as ready. 2 workers connected.
[2024-09-04 14:30:13,781] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,782] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_e95065a1602f45ff8cebc82dd1e8f3e9 (index 2) reported as ready. 3 workers connected.
[2024-09-04 14:30:13,783] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,784] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_af6f5f8ca6a9422ba8aa52dc7a9c2b23 (index 3) reported as ready. 4 workers connected.
[2024-09-04 14:30:13,784] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,785] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_1e9ecbc6d0ef4d37b19bc5d92b21c48d (index 4) reported as ready. 5 workers connected.
[2024-09-04 14:30:13,786] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,786] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_d8cf71ac6b68441592682eb1f40884c5 (index 5) reported as ready. 6 workers connected.
[2024-09-04 14:30:13,786] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,787] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,787] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_56f15b90d91744f7b0b7f6cdabee09ef (index 6) reported as ready. 7 workers connected.
[2024-09-04 14:30:13,788] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_1f503fc657224660a88ce48fb45a8474 (index 7) reported as ready. 8 workers connected.
[2024-09-04 14:30:13,788] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,789] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,790] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_21abf53018884ab8a9efb7a607bf27ef (index 8) reported as ready. 9 workers connected.
[2024-09-04 14:30:13,791] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_1956e413bd694c01a626dce83851c969 (index 9) reported as ready. 10 workers connected.
[2024-09-04 14:30:13,791] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:13,792] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:14,244] MacBook-Pro/INFO/locust.main: No run time limit set, use CTRL+C to interrupt
[2024-09-04 14:30:14,245] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:30:14,246] MacBook-Pro/INFO/locust.runners: Sending spawn jobs of 10 users at 10.00 spawn rate to 10 ready workers
[2024-09-04 14:30:14,452] MacBook-Pro/INFO/locust.runners: All users spawned: {"QianfanLLMLoadUser": 10} (10 total users)
[2024-09-04 14:30:15,329] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,330] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,331] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,335] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,349] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,425] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,473] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,616] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,616] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,620] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,650] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,702] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,723] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,743] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,817] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:15,931] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,478] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,495] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,498] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,504] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,512] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,512] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,582] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,590] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,621] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 350, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:30:16,633] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,640] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,666] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,681] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,707] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,739] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,740] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,749] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,808] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,816] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,871] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,878] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,894] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,898] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,918] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,943] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:16,954] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,000] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,003] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,006] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,030] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,055] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,055] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,063] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,084] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,091] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,093] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,103] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,164] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,164] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,171] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,208] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,244] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,256] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,272] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,280] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,286] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,294] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,355] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,369] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,412] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,423] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,446] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,457] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,464] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,479] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,479] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,484] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,522] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,537] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,545] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,559] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,571] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,583] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,587] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,622] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,643] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,662] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,672] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,704] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,712] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,725] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:17,773] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:18,082] MacBook-Pro/ERROR/locust.user.task: cannot access local variable 'header' where it is not associated with a value
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 346, in _request_internal
    'headers':header,
              ^^^^^^
UnboundLocalError: cannot access local variable 'header' where it is not associated with a value

[2024-09-04 14:30:18,572] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 696, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 350, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:30:18,574] MacBook-Pro.local/WARNING/yame.runner: Distributor[distributor] StopIteration occurs 10 times, and 10 users have been spawned.
[2024-09-04 14:30:18,577] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,577] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,578] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,578] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,578] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,578] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,578] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,579] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,579] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,582] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:30:18,659] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,659] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_e07f87b5e8cf4c7f9edc27cb2ca79cf3' (index 0) quit. 0 workers ready.
[2024-09-04 14:30:18,665] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,665] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_af6f5f8ca6a9422ba8aa52dc7a9c2b23' (index 3) quit. 0 workers ready.
[2024-09-04 14:30:18,667] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,667] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_56f15b90d91744f7b0b7f6cdabee09ef' (index 6) quit. 0 workers ready.
[2024-09-04 14:30:18,669] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_d8cf71ac6b68441592682eb1f40884c5' (index 5) quit. 0 workers ready.
[2024-09-04 14:30:18,668] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,670] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_21abf53018884ab8a9efb7a607bf27ef' (index 8) quit. 0 workers ready.
[2024-09-04 14:30:18,670] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,672] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,672] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,672] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,672] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_ca3093a24fed4c15ba543665b537a2f1' (index 1) quit. 0 workers ready.
[2024-09-04 14:30:18,674] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_1f503fc657224660a88ce48fb45a8474' (index 7) quit. 0 workers ready.
[2024-09-04 14:30:18,674] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_1956e413bd694c01a626dce83851c969' (index 9) quit. 0 workers ready.
[2024-09-04 14:30:18,675] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,675] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_e95065a1602f45ff8cebc82dd1e8f3e9' (index 2) quit. 0 workers ready.
[2024-09-04 14:30:18,677] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:30:18,677] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_1e9ecbc6d0ef4d37b19bc5d92b21c48d' (index 4) quit. 0 workers ready.
[2024-09-04 14:30:18,677] MacBook-Pro/INFO/locust.runners: The last worker quit, stopping test.
[2024-09-04 14:30:19,163] MacBook-Pro/INFO/locust.main: writing html report to file: record/20240904T143013Z/round-user_num_10/report_user_num_10.html
[2024-09-04 14:30:19,666] MacBook-Pro/INFO/locust.main: Shutting down (exit code 1)
